services:
  jaeger:
    image: jaegertracing/all-in-one:${JAEGER}
    container_name: dev-environment-jaeger-1
    restart: on-failure
    ports:
      - "5775:5775/udp"
      - "6831:6831/udp"
      - "6832:6832/udp"
      - "5778:5778"
      - "16686:16686"
      - "14268:14268"
      - "9411:9411"
      - "4318:4318"
      - "4317:4317"
    environment:
      - COLLECTOR_ZIPKIN_HTTP_PORT=9411
    networks:
      - dev-environment

volumes:
  grafana_dev_volume:
    driver: local